# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            ゲノム機能生化学分野
tagline:          '山形大'
description:      '山形大学農学部'
url:              https://yuritakeda0210.github.io/
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:           Yuri Takeda-Kimura
  name:           'ゲノム機能生化学分野'
  url:            https://yuritakeda0210.github.io/

paginate:         6
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
                                
remote_theme: fongandrew/hydeout
future: false
